services:
  nginx-fastcgi:
    image: nginx:1.25.3
    container_name: "003_nginx"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ../../projects/symfony-7:/var/www/symfony
    ports:
      - '80:80'
    networks:
      - php-benchmarks
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1gb'
  php-fpm:
    build:
      context: ../../
      dockerfile: ./runtimes/002_apache_phpfpm/fpm/phpfpm.Dockerfile
    container_name: "003_phpfpm"
    ports:
      - "9001:9001"
    networks:
      - php-benchmarks
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1gb'

networks:
  php-benchmarks:

