services:
  apache_modphp_prefork:
    build:
      context: ../../
      dockerfile: ./runtimes/001_apache_mod_php_prefork/apache.Dockerfile
    container_name: apache_modphp_prefork
    hostname: symfony7site.dev
    ports:
      - "80:80"
    networks:
      - php-benchmarks
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '1gb'
networks:
  php-benchmarks:

